services:
  web-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./project:/project
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

    command: >
      sh -c 'python manage.py runserver  0.0.0.0:8000'

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
