# Generated by Django 3.2.16 on 2023-08-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created'], 'verbose_name': 'Файлы', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created'], 'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Файл'),
        ),
    ]
