# Generated by Django 3.2.16 on 2023-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230819_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('UPD', 'Updated'), ('CHK', 'Checked')], default='NEW', max_length=3, verbose_name='Статус'),
        ),
    ]
