# Generated by Django 3.2.16 on 2023-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230819_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
