# Generated by Django 3.2.16 on 2023-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_file_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=250, unique_for_date=True, verbose_name='Слаг'),
        ),
    ]
