# Generated by Django 3.2.16 on 2023-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_file_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='updated',
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date=True, verbose_name='Слаг'),
        ),
    ]
